### ISSUE TITLE
A solution for "Import theme failed" on UE 5.4

### ISSUE THREAD

**Issue by NoSW** [brorbw/unreal-editor-themes#1]
Check if  `C:\Users\USER_NAME\AppData\Local\UnrealEngine\Slate\Themes\` directory exists. If not, create it manually and then re-import.

**Comment by brorbw** [comment]
Can you confirm that you imported the theme via the menu in the Unreal engine. Can you provide steps to reproduce. I don't have a Windows machine to test so I appreciate all input.

**Comment by kaze-gif** [comment]
I can confirm that this worked for me, UE 5.4 on Windows 11.

**Comment by brorbw** [comment]
Fixed by f9045e1

**Comment by lromixl** [comment]
Can confirm that manually creating these folders helped. But it should be automatic, right? Tested with UE 5.6 from launcher

**Comment by brorbw** [comment]
It should be, but it should be handled by the engine. I'm not on Windows so I can't properly test this
